# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='upload_material',
        ),
        migrations.AddField(
            model_name='helper',
            name='up_material',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
