# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('discipline_name', models.CharField(max_length=50)),
                ('discipline_year', models.IntegerField()),
                ('upload_material', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
    ]
