# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20161118_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.AlterField(
            model_name='help_materials',
            name='upload_material',
            field=models.FileField(upload_to='downloads/'),
        ),
    ]
