# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0004_auto_20161118_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='help_materials',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='help_materials',
            name='users',
            field=models.ManyToManyField(related_name='my_material', to=settings.AUTH_USER_MODEL),
        ),
    ]
